version: '3.8'
services:
  server:
    container_name: pandabi-backend
    build:
      context: ./
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    restart: always
    env_file:
      - ./.env
    command: "/bin/bash startup.sh"

networks:
  default:
    driver: bridge
